### ISSUE TITLE
pvt实验结果

### ISSUE THREAD

**Issue by CHANTILLY2023** [ChunmingHe/FEDER#13]
你好，请问一下可以提供pvt做骨干网络的实验结果和预训练模型吗？因为需要跟你的方法进行对比，所以我手动重新训练了几次，但是每次结果跟原论文里指标比都不太理想，很迷茫不知道问题在哪里。

**Comment by ChunmingHe** [comment]
您好，表1里面好像没有pvt哇，或者我没理解清楚，如果方便的话，还请加我微信，我们详聊吧 15112561951

CHANTILLY2023 ***@***.***> 于2024年10月2日周三 18:21写道：
